/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/~__root'
import { Route as UsersIndexRouteImport } from './../routes/~users/~index'
import { Route as SetupIndexRouteImport } from './../routes/~setup/~index'
import { Route as SessionTestIndexRouteImport } from './../routes/~session-test/~index'
import { Route as CallbackIndexRouteImport } from './../routes/~callback/~index'
import { Route as indexIndexRouteImport } from './../routes/~(index)/~index'
import { Route as IdIndexRouteImport } from './../routes/~$id/~index'

const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTestIndexRoute = SessionTestIndexRouteImport.update({
  id: '/session-test/',
  path: '/session-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const indexIndexRoute = indexIndexRouteImport.update({
  id: '/(index)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdIndexRoute = IdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$id/': typeof IdIndexRoute
  '/': typeof indexIndexRoute
  '/callback/': typeof CallbackIndexRoute
  '/session-test/': typeof SessionTestIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/$id': typeof IdIndexRoute
  '/': typeof indexIndexRoute
  '/callback': typeof CallbackIndexRoute
  '/session-test': typeof SessionTestIndexRoute
  '/setup': typeof SetupIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$id/': typeof IdIndexRoute
  '/(index)/': typeof indexIndexRoute
  '/callback/': typeof CallbackIndexRoute
  '/session-test/': typeof SessionTestIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$id/'
    | '/'
    | '/callback/'
    | '/session-test/'
    | '/setup/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$id' | '/' | '/callback' | '/session-test' | '/setup' | '/users'
  id:
    | '__root__'
    | '/$id/'
    | '/(index)/'
    | '/callback/'
    | '/session-test/'
    | '/setup/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IdIndexRoute: typeof IdIndexRoute
  indexIndexRoute: typeof indexIndexRoute
  CallbackIndexRoute: typeof CallbackIndexRoute
  SessionTestIndexRoute: typeof SessionTestIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-test/': {
      id: '/session-test/'
      path: '/session-test'
      fullPath: '/session-test/'
      preLoaderRoute: typeof SessionTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback/'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/': {
      id: '/(index)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/': {
      id: '/$id/'
      path: '/$id'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IdIndexRoute: IdIndexRoute,
  indexIndexRoute: indexIndexRoute,
  CallbackIndexRoute: CallbackIndexRoute,
  SessionTestIndexRoute: SessionTestIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
