/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/~__root'
import { Route as UsersIndexRouteImport } from './../routes/~users/~index'
import { Route as SetupIndexRouteImport } from './../routes/~setup/~index'
import { Route as SessionTestIndexRouteImport } from './../routes/~session-test/~index'
import { Route as ConfigIndexRouteImport } from './../routes/~config/~index'
import { Route as CallbackIndexRouteImport } from './../routes/~callback/~index'
import { Route as indexIndexRouteImport } from './../routes/~(index)/~index'
import { Route as ServerIdIndexRouteImport } from './../routes/~$serverId/~index'
import { Route as ConfigServerIdIndexRouteImport } from './../routes/~config/~$serverId/~index'
import { Route as ServerIdChatIdIndexRouteImport } from './../routes/~$serverId/~$chatId/~index'

const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTestIndexRoute = SessionTestIndexRouteImport.update({
  id: '/session-test/',
  path: '/session-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const indexIndexRoute = indexIndexRouteImport.update({
  id: '/(index)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerIdIndexRoute = ServerIdIndexRouteImport.update({
  id: '/$serverId/',
  path: '/$serverId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigServerIdIndexRoute = ConfigServerIdIndexRouteImport.update({
  id: '/config/$serverId/',
  path: '/config/$serverId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerIdChatIdIndexRoute = ServerIdChatIdIndexRouteImport.update({
  id: '/$serverId/$chatId/',
  path: '/$serverId/$chatId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$serverId/': typeof ServerIdIndexRoute
  '/': typeof indexIndexRoute
  '/callback/': typeof CallbackIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/session-test/': typeof SessionTestIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$serverId/$chatId/': typeof ServerIdChatIdIndexRoute
  '/config/$serverId/': typeof ConfigServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/$serverId': typeof ServerIdIndexRoute
  '/': typeof indexIndexRoute
  '/callback': typeof CallbackIndexRoute
  '/config': typeof ConfigIndexRoute
  '/session-test': typeof SessionTestIndexRoute
  '/setup': typeof SetupIndexRoute
  '/users': typeof UsersIndexRoute
  '/$serverId/$chatId': typeof ServerIdChatIdIndexRoute
  '/config/$serverId': typeof ConfigServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$serverId/': typeof ServerIdIndexRoute
  '/(index)/': typeof indexIndexRoute
  '/callback/': typeof CallbackIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/session-test/': typeof SessionTestIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$serverId/$chatId/': typeof ServerIdChatIdIndexRoute
  '/config/$serverId/': typeof ConfigServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$serverId/'
    | '/'
    | '/callback/'
    | '/config/'
    | '/session-test/'
    | '/setup/'
    | '/users/'
    | '/$serverId/$chatId/'
    | '/config/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$serverId'
    | '/'
    | '/callback'
    | '/config'
    | '/session-test'
    | '/setup'
    | '/users'
    | '/$serverId/$chatId'
    | '/config/$serverId'
  id:
    | '__root__'
    | '/$serverId/'
    | '/(index)/'
    | '/callback/'
    | '/config/'
    | '/session-test/'
    | '/setup/'
    | '/users/'
    | '/$serverId/$chatId/'
    | '/config/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ServerIdIndexRoute: typeof ServerIdIndexRoute
  indexIndexRoute: typeof indexIndexRoute
  CallbackIndexRoute: typeof CallbackIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  SessionTestIndexRoute: typeof SessionTestIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ServerIdChatIdIndexRoute: typeof ServerIdChatIdIndexRoute
  ConfigServerIdIndexRoute: typeof ConfigServerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-test/': {
      id: '/session-test/'
      path: '/session-test'
      fullPath: '/session-test/'
      preLoaderRoute: typeof SessionTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback/'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/': {
      id: '/(index)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serverId/': {
      id: '/$serverId/'
      path: '/$serverId'
      fullPath: '/$serverId/'
      preLoaderRoute: typeof ServerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/$serverId/': {
      id: '/config/$serverId/'
      path: '/config/$serverId'
      fullPath: '/config/$serverId/'
      preLoaderRoute: typeof ConfigServerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serverId/$chatId/': {
      id: '/$serverId/$chatId/'
      path: '/$serverId/$chatId'
      fullPath: '/$serverId/$chatId/'
      preLoaderRoute: typeof ServerIdChatIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ServerIdIndexRoute: ServerIdIndexRoute,
  indexIndexRoute: indexIndexRoute,
  CallbackIndexRoute: CallbackIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  SessionTestIndexRoute: SessionTestIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ServerIdChatIdIndexRoute: ServerIdChatIdIndexRoute,
  ConfigServerIdIndexRoute: ConfigServerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
