
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ClientType = {
  WEB: 'WEB',
  EXPO: 'EXPO'
} as const

export type ClientType = (typeof ClientType)[keyof typeof ClientType]


export const SessionStatus = {
  ACTIVE: 'ACTIVE',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
} as const

export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus]


export const NoActiveReason = {
  LOGOUT_CURRENT: 'LOGOUT_CURRENT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  REUSE_DETECTED: 'REUSE_DETECTED',
  MANUAL_REVOKE: 'MANUAL_REVOKE',
  LOCKDOWN: 'LOCKDOWN',
  EXPIRED: 'EXPIRED'
} as const

export type NoActiveReason = (typeof NoActiveReason)[keyof typeof NoActiveReason]


export const UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  ROOT: 'ROOT'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]
