/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/~__root'
import { Route as UsersRouteImport } from './../routes/~users'
import { Route as SetupRouteImport } from './../routes/~setup'
import { Route as SessionTestRouteImport } from './../routes/~session-test'
import { Route as CallbackRouteImport } from './../routes/~callback'
import { Route as IndexRouteImport } from './../routes/~index'
import { Route as KeyIndexRouteImport } from './../routes/~$key/~index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTestRoute = SessionTestRouteImport.update({
  id: '/session-test',
  path: '/session-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyIndexRoute = KeyIndexRouteImport.update({
  id: '/$key/',
  path: '/$key/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/session-test': typeof SessionTestRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/$key/': typeof KeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/session-test': typeof SessionTestRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/$key': typeof KeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/session-test': typeof SessionTestRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/$key/': typeof KeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/session-test'
    | '/setup'
    | '/users'
    | '/$key/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/callback' | '/session-test' | '/setup' | '/users' | '/$key'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/session-test'
    | '/setup'
    | '/users'
    | '/$key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  SessionTestRoute: typeof SessionTestRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
  KeyIndexRoute: typeof KeyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-test': {
      id: '/session-test'
      path: '/session-test'
      fullPath: '/session-test'
      preLoaderRoute: typeof SessionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$key/': {
      id: '/$key/'
      path: '/$key'
      fullPath: '/$key/'
      preLoaderRoute: typeof KeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  SessionTestRoute: SessionTestRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
  KeyIndexRoute: KeyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
