/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/~__root'
import { Route as UsersRouteImport } from './../routes/~users'
import { Route as SessionTestRouteImport } from './../routes/~session-test'
import { Route as IndexRouteImport } from './../routes/~index'
import { Route as KeyIndexRouteImport } from './../routes/~$key/~index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTestRoute = SessionTestRouteImport.update({
  id: '/session-test',
  path: '/session-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyIndexRoute = KeyIndexRouteImport.update({
  id: '/$key/',
  path: '/$key/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session-test': typeof SessionTestRoute
  '/users': typeof UsersRoute
  '/$key/': typeof KeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session-test': typeof SessionTestRoute
  '/users': typeof UsersRoute
  '/$key': typeof KeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session-test': typeof SessionTestRoute
  '/users': typeof UsersRoute
  '/$key/': typeof KeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session-test' | '/users' | '/$key/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session-test' | '/users' | '/$key'
  id: '__root__' | '/' | '/session-test' | '/users' | '/$key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionTestRoute: typeof SessionTestRoute
  UsersRoute: typeof UsersRoute
  KeyIndexRoute: typeof KeyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-test': {
      id: '/session-test'
      path: '/session-test'
      fullPath: '/session-test'
      preLoaderRoute: typeof SessionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$key/': {
      id: '/$key/'
      path: '/$key'
      fullPath: '/$key/'
      preLoaderRoute: typeof KeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionTestRoute: SessionTestRoute,
  UsersRoute: UsersRoute,
  KeyIndexRoute: KeyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
